In [4]:
import os
import numpy as np
os.chdir("/Users/coulaud/Documents/DL-normalization")
os.getcwd()
data_dir = "data/processed/newdata/"


In [2]:
def addMap(X, dist_map):
    _,H,W  = X.shape

    Y    = np.empty((4,H,W))
    Y[0] = X[0,:,:]
    Y[1] = X[1,:,:]
    Y[2] = X[2,:,:]
    Y[3] = dist_map
    return Y    

def rota_90(X):
    _,H,W  = X.shape
      
    alphas_i = np.rot90(X[0,:,:], k=1, axes=(0,1))
    alphas_j = np.rot90(X[1,:,:], k=1, axes=(0,1))
    w        = np.rot90(X[2,:,:], k=1, axes=(0,1))
    dist_map = np.rot90(X[3,:,:], k=1, axes=(0,1))
    alphas_i = np.roll(alphas_i, -1, axis = 1)
    
    X    = np.empty((4,W,H))
    X[0] = alphas_j
    X[1] = alphas_i
    X[2] = w
    X[3] = dist_map
    return X

def rota_180(X):
    _,H,W  = X.shape
    
    alphas_i = np.rot90(X[0,:,:], k=2, axes=(0,1))
    alphas_j = np.rot90(X[1,:,:], k=2, axes=(0,1))
    w        = np.rot90(X[2,:,:], k=2, axes=(0,1))
    dist_map = np.rot90(X[3,:,:], k=2, axes=(0,1))
    alphas_j = np.roll(alphas_j, -1, axis = 1)
    alphas_i = np.roll(alphas_i, 1, axis = 0)
    
    X    = np.empty((4,H,W))
    X[0] = alphas_i
    X[1] = alphas_j
    X[2] = w
    X[3] = dist_map
    return X

def rota_270(X):
    _,H,W  = X.shape
        
    alphas_i = np.rot90(X[0,:,:], k=1, axes=(1,0))
    alphas_j = np.rot90(X[1,:,:], k=1, axes=(1,0))
    w        = np.rot90(X[2,:,:], k=1, axes=(1,0))
    dist_map = np.rot90(X[3,:,:], k=1, axes=(1,0))
    alphas_j = np.roll(alphas_j, 1, axis = 0)
    
    X    = np.empty((4,W,H))
    X[0] = alphas_j
    X[1] = alphas_i
    X[2] = w
    X[3] = dist_map
    return X

def flip_vert(X):
    _,H,W  = X.shape

    alphas_i = np.flipud(X[0,:,:])
    alphas_j = np.flipud(X[1,:,:])
    w        = np.flipud(X[2,:,:])
    dist_map = np.flipud(X[3,:,:])
    alphas_i = np.roll(alphas_i, 1, axis = 0)
    X    = np.empty((4,H,W))
    X[0] = alphas_i
    X[1] = alphas_j
    X[2] = w
    X[3] = dist_map
    return X

def flip_hor(X):
    _,H,W  = X.shape

    alphas_i = np.fliplr(X[0,:,:])
    alphas_j = np.fliplr(X[1,:,:])
    w        = np.fliplr(X[2,:,:])
    dist_map = np.fliplr(X[3,:,:])
    alphas_j = np.roll(alphas_j, -1, axis = 1)
    X    = np.empty((4,H,W))
    X[0] = alphas_i
    X[1] = alphas_j
    X[2] = w
    X[3] = dist_map
    return X

In [5]:
X = addMap(np.load(data_dir+"valid/X/NORSSH_BND_PERTEN13.npz")['arr_0'], np.load("data/sign_dist_map_std.npz")['arr_0'])

In [6]:
np.array_equal(flip_hor(flip_vert(X)),flip_vert(flip_hor(X)))

True

In [7]:
np.array_equal(flip_vert(flip_hor(X)),rota_180(X))

True

In [8]:
np.array_equal(rota_180(rota_180(X)),X)

True

In [9]:
np.array_equal(rota_90(rota_90(X)),rota_180(X))

True

In [10]:
np.array_equal(rota_270(rota_270(X)),rota_180(X))

True

In [11]:
np.array_equal(rota_90(rota_180(X)),rota_270(X)), np.array_equal(rota_180(rota_90(X)),rota_270(X))

(True, True)

In [12]:
np.array_equal(rota_90(rota_90(rota_90(X))),rota_270(X))

True

In [13]:
np.array_equal(rota_90(rota_90(rota_90(rota_90(X)))),X)

True

In [14]:
np.array_equal(rota_270(rota_270(rota_270(rota_270(X)))),X)

True

In [15]:
np.array_equal(flip_vert(flip_hor(flip_vert(flip_hor(X)))),X)

True

In [29]:
np.array_equal(rota_90(rota_270(X)),rota_270(rota_90(X))), np.array_equal(rota_90(rota_270(X)),X), np.array_equal(X,rota_90(rota_270(X)))

(True, True, True)

In [27]:
t = np.array([[j+i for i in range(6)] for j in range(1,36,6)])
print(t)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [36]:
Xt = np.empty((4,6,6),int)

for i in range(4) : Xt[i] = t

In [46]:
rota_180(Xt)

array([[[ 6.,  5.,  4.,  3.,  2.,  1.],
        [36., 35., 34., 33., 32., 31.],
        [30., 29., 28., 27., 26., 25.],
        [24., 23., 22., 21., 20., 19.],
        [18., 17., 16., 15., 14., 13.],
        [12., 11., 10.,  9.,  8.,  7.]],

       [[35., 34., 33., 32., 31., 36.],
        [29., 28., 27., 26., 25., 30.],
        [23., 22., 21., 20., 19., 24.],
        [17., 16., 15., 14., 13., 18.],
        [11., 10.,  9.,  8.,  7., 12.],
        [ 5.,  4.,  3.,  2.,  1.,  6.]],

       [[36., 35., 34., 33., 32., 31.],
        [30., 29., 28., 27., 26., 25.],
        [24., 23., 22., 21., 20., 19.],
        [18., 17., 16., 15., 14., 13.],
        [12., 11., 10.,  9.,  8.,  7.],
        [ 6.,  5.,  4.,  3.,  2.,  1.]],

       [[36., 35., 34., 33., 32., 31.],
        [30., 29., 28., 27., 26., 25.],
        [24., 23., 22., 21., 20., 19.],
        [18., 17., 16., 15., 14., 13.],
        [12., 11., 10.,  9.,  8.,  7.],
        [ 6.,  5.,  4.,  3.,  2.,  1.]]])